return {
	Text = "₸",
	Method = "m",
	Function = "⨍",
	Constructor = "🛠",
	Field = "",
	Variable = "",
	Class = "🖧",
	Interface = "",
	Module = "",
	Property = "",
	Unit = "",
	Value = "",
	Enum = "",
	Keyword = "⚿",
	Snippet = "",
	Color = "",
	File = "🖹",
	Reference = "",
	Folder = "",
	EnumMember = "",
	Constant = "ℇ",
	Struct = "",
	Event = "",
	Operator = "",
	TypeParameter = "ナ",
	Codeium = "✨",
}
