require("config.autocommands")
require("config.diagnostics")
require("config.keymap")
require("config.pretty_help_windows")
require("config.setopts")

vim.api.nvim_command("command! WQ wq")
vim.api.nvim_command("command! Wq wq")
vim.api.nvim_command("command! W w")
vim.api.nvim_command("command! Q q")
